### PR TITLE
show-solar-panels-needed

### PR DESCRIPTION
**Pull request by TobbyJay**
I redesigned the result page and wrote an algorithm to display a recommended amount of solar panels needed to run all the applinces listed based on the result gotten from the Solar power needed

### CODE REVIEW

**Comment by ngwutadesmond** [comment]
Awesome but before merging have you test run it?

**Comment by TobbyJay** [comment]
@chydee i have test ran it and it is working fine. just test ran again for final confirmation

**Comment by ngwutadesmond** [comment]
Okay assign me as the reviewer or just merge

**Comment by ngwutadesmond** [comment]
Merged

**Comment by TobbyJay** [comment]
you have already been assigned @chydee

**Comment by TobbyJay** [comment]
oh ok, thanks

**Comment by ngwutadesmond** [comment]
Go ahead and create the APK and upload

**Pull request merged**
